// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt7QK3rXnuGZmCiTKg4Q1fgXwT8_G6Ry4',
    appId: '1:770011628536:web:fae7ade4e2b7d673a18c0d',
    messagingSenderId: '770011628536',
    projectId: 'aarogya-sahayak-275ca',
    authDomain: 'aarogya-sahayak-275ca.firebaseapp.com',
    storageBucket: 'aarogya-sahayak-275ca.firebasestorage.app',
    measurementId: 'G-5B0X3VWSDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpolN3ihXBdz1YsWcPssl7brfCu8_vW4E',
    appId: '1:770011628536:android:b134e1ca330d312ea18c0d',
    messagingSenderId: '770011628536',
    projectId: 'aarogya-sahayak-275ca',
    storageBucket: 'aarogya-sahayak-275ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbEYyDyU2mMCp540dsP02e5WHkUNEeXwc',
    appId: '1:770011628536:ios:c774ffd3da05a773a18c0d',
    messagingSenderId: '770011628536',
    projectId: 'aarogya-sahayak-275ca',
    storageBucket: 'aarogya-sahayak-275ca.firebasestorage.app',
    iosBundleId: 'com.example.aarogyaSahayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbEYyDyU2mMCp540dsP02e5WHkUNEeXwc',
    appId: '1:770011628536:ios:c774ffd3da05a773a18c0d',
    messagingSenderId: '770011628536',
    projectId: 'aarogya-sahayak-275ca',
    storageBucket: 'aarogya-sahayak-275ca.firebasestorage.app',
    iosBundleId: 'com.example.aarogyaSahayak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt7QK3rXnuGZmCiTKg4Q1fgXwT8_G6Ry4',
    appId: '1:770011628536:web:f5923906c0f45b8fa18c0d',
    messagingSenderId: '770011628536',
    projectId: 'aarogya-sahayak-275ca',
    authDomain: 'aarogya-sahayak-275ca.firebaseapp.com',
    storageBucket: 'aarogya-sahayak-275ca.firebasestorage.app',
    measurementId: 'G-B3RF8KQ222',
  );
}
